replaced [8]byte with types.NamespaceID
celestiaorg/rollmint pull request #554
Opened 2022-10-10 11:57 UTC by randomshinichi

I think naming the new type NamespaceID is straightforward and requires no further explanation.

Let me know if I missed something - the go compiler likes it just fine

2022-10-10 13:50 UTC, tzdybal requested changes
Thanks for your submission! It looks really good.

Please fix the failing unit tests.

2022-10-11 12:23 UTC, randomshinichi commented
Just fixed the unittest, should work now (tested locally)

2022-10-13 06:53 UTC, tzdybal approved these changes

2022-10-13 12:18 UTC, nashqueue requested changes
Looks good :) Why are 4 Tests skipped in github?

2022-10-13 19:17 UTC, merged